Convert module to v3 format
bitfocus/companion-module-dashare-multiplay pull request #4
Opened 2023-06-24 12:00 UTC by peternewman

My first time doing this, and I've not tested against the software, but the expected commands appear in a Telnet window.

I figured this was a good way to start before looking at #2 / #3

2023-06-24 13:37 UTC, dnmeid requested changes

2023-06-24 13:37 UTC, dnmeid commented on index.js
> +		var self = this
prefer let, subsequently you are mixing usage of self and this.

2023-06-24 13:37 UTC, dnmeid commented on index.js
> +		var self = this
prefer let

2023-06-24 13:37 UTC, dnmeid commented on index.js
> +		if (self.config.host) {
should check for existance **and** validiy of host **and** port

2023-06-24 13:37 UTC, dnmeid commented on index.js
> +		var self = this
let again, or better just get rid of this self pattern when it is not needed.

2023-06-24 13:37 UTC, dnmeid commented on package.json
Remove keywords, which are now in manifest.json

2023-06-24 13:37 UTC, dnmeid commented on presets.js
> +exports.getPresets = function (self) {
you are passing self but not using it

2023-06-24 22:25 UTC, peternewman commented on index.js
> +	async configUpdated(config) {
Sorry, removed.

2023-06-24 22:26 UTC, peternewman commented on index.js
> +		var self = this
Having now read up on it, I've switched almost all var to let.

2023-06-24 22:26 UTC, peternewman commented on index.js
> +		this.log('info', 'logged in')
I think this was tech debt from the original installation, so I've removed it (as well as the login tracking which didn't ever seem to be set to true).

2023-06-24 22:27 UTC, peternewman commented on index.js
> +var debug
Removed as it seemed to be redundant.

2023-06-24 22:28 UTC, peternewman commented on index.js
> +var log
Again.

2023-06-24 22:28 UTC, peternewman commented on index.js
> +		var self = this
Switched practically everything to this where possible.

2023-06-24 22:28 UTC, peternewman commented on index.js
> +		var self = this
Again switched to this.

2023-06-24 22:29 UTC, peternewman commented on index.js
> +		if (self.config.host) {
What exactly do you mean, won't the Regex handle that?

2023-06-24 22:30 UTC, peternewman commented on index.js
> +		var self = this
Removed.

2023-06-24 22:30 UTC, peternewman commented on package.json
Done

2023-06-24 22:30 UTC, peternewman commented on presets.js
> +exports.getPresets = function (self) {
Removed.

2023-06-24 22:33 UTC, peternewman commented on index.js
> +		this.log('debug', data)
I'm assuming/I don't believe there is much returned data (aside from possibly the version command which I've currently not implemented). I don't currently have a running older release with Telnet, but I was migrating the module to v3 before trying to add the current (beta) OSC support.

2023-06-24 22:34 UTC, peternewman commented on index.js
> +		this.updateStatus(InstanceStatus.Ok, 'Received data')
I can't see a way to get the current status, do I have to double track it locally?

2023-06-24 22:35 UTC, peternewman commented on index.js
> +var actions = require('./actions')
Done

2023-06-24 22:35 UTC, peternewman commented on index.js
> +var presets = require('./presets')
Done

2023-06-24 22:39 UTC, peternewman commented
Thanks @dnmeid . As you can probably tell I'm not a JS expert (or at least not anything as modern as this) so thanks for the pointers. This is also my first time working on a companion module.

As a general thought, given there's a fairly finite number of common comms methods (e.g. TCP, UDP, Telnet, HTTP, OSC), are there, or would there be benefit in, some basic starter/template modules people could work from, without all the complexity of say the generic ones, and that might have less bad habits than working from other existing modules?

2023-06-25 12:47 UTC, dnmeid commented on index.js
> +		this.updateStatus(InstanceStatus.Ok, 'Received data')
Yes, it depends on how the module makes use of the status and how it depends on the device or communication. We just want to make sure there is no flooding of status updates (possible DoS).

2023-06-25 12:55 UTC, dnmeid commented on index.js
> +		if (self.config.host) {
Yes and no. In actions or feedbacks the regex is just a visual hint, in the configuration you can't hit save if the regex doesn't match. This check in the config has not been there from the start so there may be configurations with illegal data. Also some users edit the configuration database by hand. It is always a good idea to do some extra checks. Minimum goal is that the module doesn't crash if it gets invalid data. You can go as complicated as you want.

2023-06-25 13:02 UTC, dnmeid commented
Don't worry if it is not perfect from the start. It will never be. After each release you will find things to improve.

> As a general thought, given there's a fairly finite number of common comms methods (e.g. TCP, UDP, Telnet, HTTP, OSC), are there, or would there be benefit in, some basic starter/template modules people could work from, without all the complexity of say the generic ones, and that might have less bad habits than working from other existing modules?

That would be nice, but we need somebody to do it. It is allready a lot of work to code new features, find bugs, review PRs, update modules, give support to developers and users, write documentation...

2023-07-14 17:41 UTC, peternewman commented on index.js
> +		this.updateStatus(InstanceStatus.Ok, 'Received data')
I've added some basic functionality, but it seems very backwards to me that companion-module-base couldn't deal with this under the hood using effectively the same code, to save each module author having to reinvent the wheel.

2023-07-14 17:47 UTC, peternewman commented on index.js
> +		if (self.config.host) {
So it turns out I'd not changed from `this.REGEX_IP` to `Regex.IP` and it was silently dropping all regex checks in the config, without throwing any errors during build, so that was a good fix at least.

Can you point me at another module that does this I could learn from, I've got something that actually works (but haven't committed it), after the obvious thing didn't work because a regex string needs `foo` whereas a regex literal needs `/foo/` in JS!

Again it feels like we want to nick a chunk of:
https://github.com/bitfocus/companion/blob/master/webui/src/Components/TextInputField.jsx#L56-L66

Into companion-module-base if we're going to do this, and fetch the config from getConfigFields, so I just pass in the field name, and maybe the variable, and it gives me a boolean result, again rather than everyone reinventing the wheel badly/with different edge cases.

2023-07-14 17:50 UTC, peternewman commented
> That would be nice, but we need somebody to do it. It is allready a lot of work to code new features, find bugs, review PRs, update modules, give support to developers and users, write documentation...

Yeah fair point, in which case to turn that slightly on its head, as a developer of a new module I want to find a good HTTP example to work from say, without lots of trawling through code, its hard to know which modules talk via HTTP, so could there be a list of the top few HTTP based modules for me to go and look at? Obviously likewise for other high level protocols. Which is fairly minimal extra effort and might remove some of the developer support required. Plus then at least someone will be starting from a good base rather than the first one they come across which might have lots of issues...

2023-07-16 12:19 UTC, dnmeid requested changes

2023-07-16 12:19 UTC, dnmeid commented on package.json
> +		"@companion-module/tools": "^0.5.1"
Please update

2023-07-16 12:19 UTC, dnmeid commented on index.js
> +		this.initPresets()
Your presets do not depend on the configuration and are not dynamic, so why rebuild them when config is updated?

2023-07-16 12:19 UTC, dnmeid commented on index.js
> +			this.localStatusMessage = undefined
Does this work as intended?
If you set your local variables to undefined after each successful update, the if will always be true in the next call.

2023-07-17 10:36 UTC, peternewman commented on index.js
> +		this.initPresets()
Removed.

2023-07-17 10:37 UTC, peternewman commented on index.js
> +			this.localStatusMessage = undefined
Oops, fixed. TBH this is exactly the sort of silly copy/paste errors that having it built into the module code would avoid.

2023-07-17 10:56 UTC, peternewman commented on package.json
> +		"@companion-module/tools": "^0.5.1"
Done, and I've added dependabot too.

2023-07-17 15:49 UTC, dnmeid approved these changes

2023-07-17 15:50 UTC, merged